# File: .github/workflows/azure/azure-login-sp.yml
name: Run Azure Login With a Service Principal Secret

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          az account show
